### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by coder-lg**
I found a typo, so I fixed it for you. Is this fine?

### CODE REVIEW

**Comment by coder-lg** [comment]
@Naresh1318

**Comment by coder-lg** [comment]
yo @Naresh1318

**Review by Naresh1318 — APPROVED** [review]
Thanks for making the change!

**Comment by coder-lg** [comment]
Anytime! Great theme too!

**Comment by coder-lg** [comment]
You can go ahead and merge it now :)

**Pull request merged**
